## KNN ASSIGNMENT - 2

### Step - 1: Load the data

In [8]:
import pandas as pd

In [9]:
data = pd.read_csv(r"C:\Users\sreej\Downloads\diamonds (1).csv")
data.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

### Step - 2: identify input and output variables

In [10]:
x = data.drop('price', axis = 1)
y = data['price']

### Step - 3: Split the data - Test and Train (recommended 75:25 split)

In [11]:
from sklearn.model_selection import train_test_split

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42, test_size = 0.25)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((40455, 9), (13485, 9), (40455,), (13485,))

### Step - 4: Data Preprocessing on X_train (You can use sklearn for data preprocessing)
    - Categorical Data Encoding
    - Numerical Data Rescaling


In [48]:
cat_col = ['cut', 'color', 'clarity']
cat_col

['cut', 'color', 'clarity']

In [49]:
num_col = ['carat', 'depth', 'table', 'x', 'y', 'z']
num_col

['carat', 'depth', 'table', 'x', 'y', 'z']

Categorical Data

In [50]:
from sklearn.preprocessing import OneHotEncoder

In [51]:
ohe = OneHotEncoder(sparse_output = False)
ohe

OneHotEncoder(sparse_output=False)

In [52]:
ohe_cat = ohe.fit_transform(x_train[cat_col])

In [53]:
ohe_cat = pd.DataFrame(ohe_cat)
ohe_cat.head()

0    1    2    3    4    5    6   ...   13   14   15   16   17   18   19
0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0
1  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0  0.0
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0

[5 rows x 20 columns]

Numerical Data

In [54]:
from sklearn.preprocessing import StandardScaler

In [55]:
std = StandardScaler()
std

StandardScaler()

In [56]:
std_num = std.fit_transform(x_train[num_col])

In [57]:
std_num = pd.DataFrame(std_num)
std_num.head()

0         1         2         3         4         5
0 -1.156665  2.207837  0.242414 -1.589985 -1.544446 -1.365816
1  0.086917  0.038517 -0.654923  0.273560  0.291506  0.282149
2  0.529547 -0.451329  0.242414  0.737217  0.676181  0.634279
3  0.466314 -0.731242 -0.654923  0.710468  0.667439  0.577938
4 -0.397869  0.038517 -0.206254 -0.270345 -0.233052 -0.239002

Combine Numerical and Categorical

In [62]:
import numpy as np

In [65]:
combine_train = np.hstack((ohe_cat, std_num))
combine_train

array([[ 0.        ,  1.        ,  0.        , ..., -1.58998506,
        -1.54444639, -1.36581585],
       [ 0.        ,  0.        ,  1.        , ...,  0.27356006,
         0.29150568,  0.28214948],
       [ 0.        ,  0.        ,  0.        , ...,  0.73721722,
         0.67618135,  0.63427882],
       ...,
       [ 0.        ,  0.        ,  0.        , ..., -1.10849493,
        -1.11605757, -1.18270859],
       [ 0.        ,  0.        ,  0.        , ...,  0.35380841,
         0.25653516,  0.39483087],
       [ 0.        ,  0.        ,  0.        , ...,  0.9690458 ,
         0.92097496,  0.80330091]], shape=(40455, 26))

### Step - 5: Data Preprocessing on X_test 

In [58]:
num_test = ohe.transform(x_test[cat_col])
num_test

array([[0., 0., 1., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(13485, 20))

In [59]:
cat_test = std.transform(x_test[num_col])
cat_test

array([[-1.1777423 ,  0.24845108, -0.65492279, -1.57215209, -1.5182185 ,
        -1.50666759],
       [-0.46110219, -1.22108813, -0.20625438, -0.26142897, -0.2767652 ,
        -0.39393886],
       [-0.8404999 ,  0.24845108, -1.1035912 , -0.86774987, -0.87126397,
        -0.83057925],
       ...,
       [ 0.86678978,  0.45838525, -1.55225961,  1.00471173,  0.92971759,
         1.01457852],
       [ 0.44523677,  0.31842913,  0.69108244,  0.60346996,  0.62372557,
         0.648364  ],
       [ 0.50846972,  0.73829748,  0.69108244,  0.65696887,  0.59749769,
         0.71878987]], shape=(13485, 6))

In [67]:
combine_test = np.hstack((num_test, cat_test))
combine_test

array([[ 0.        ,  0.        ,  1.        , ..., -1.57215209,
        -1.5182185 , -1.50666759],
       [ 0.        ,  0.        ,  0.        , ..., -0.26142897,
        -0.2767652 , -0.39393886],
       [ 0.        ,  0.        ,  1.        , ..., -0.86774987,
        -0.87126397, -0.83057925],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  1.00471173,
         0.92971759,  1.01457852],
       [ 0.        ,  0.        ,  0.        , ...,  0.60346996,
         0.62372557,  0.648364  ],
       [ 0.        ,  0.        ,  0.        , ...,  0.65696887,
         0.59749769,  0.71878987]], shape=(13485, 26))

### Step - 6: Build the model and predict on X_test (SCRATCH IMPLEMENTATION)
Implement KNN Algorithm from scratch and do the predictions for test data. You should not use the sklearn KNN algorithm here. Write the complete code implementation from scratch for KNN algorithm.

In [60]:
import numpy as np

class KNNRegressorScratch:
    def __init__(self, k=5):
        self.k = k

    def fit(self, x, y):
        self.x_train = x
        self.y_train = y.values

    def euclidean_distance(self, x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))

    def predict(self, x_test):
        predictions = []

        for x in x_test:
            distances = []
            for i, x_train in enumerate(self.x_train):
                dist = self.euclidean_distance(x, x_train)
                distances.append((dist, self.y_train[i]))

            # Sort by distance
            distances.sort(key=lambda x: x[0])

            # Take k nearest neighbors
            k_nearest = distances[:self.k]

            # Average of k neighbors
            avg_price = np.mean([price for _, price in k_nearest])
            predictions.append(avg_price)

        return np.array(predictions)


In [71]:
knn_scratch = KNNRegressorScratch(k=5)
knn_scratch.fit(combine_test, y_train)

y_pred_scratch = knn_scratch.predict(combine_test)

### Step - 7: Evaluate your model


In [72]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

Scratch KNN Evaluation Results

In [86]:
mae_sc = mean_absolute_error(y_test, y_pred_scratch)
mse_sc = mean_squared_error(y_test, y_pred_scratch)
rmse_sc = np.sqrt(mse_sc)
r2 = r2_score(y_test, y_pred_scratch)

print("MAE :", mae_sc)
print("MSE :", mse_sc)
print("RMSE:", rmse_sc)
print("R²  :", r2)

MAE : 3276.2378642936596
MSE : 19054422.899150167
RMSE: 4365.137214240827
R²  : -0.21290876243187085


### Step - 8: Train a model using sklearn KNN Algorithm and compare the results with your scratch implementation

In [73]:
from sklearn.neighbors import KNeighborsRegressor

In [74]:
knr = KNeighborsRegressor(n_neighbors = 5)
knr

KNeighborsRegressor()

In [75]:
knr.fit(combine_train, y_train)

KNeighborsRegressor()

In [76]:
y_pred_sklearn = knr.predict(combine_test)
y_pred_sklearn

array([ 586.4, 2427.6, 1083.4, ..., 8944.4, 4548.8, 4121.4],
      shape=(13485,))

Sklearn KNN Evaluation Results

In [87]:
mae_sk = mean_absolute_error(y_test, y_pred_sklearn)
mse_sk = mean_squared_error(y_test, y_pred_sklearn)
rmse_sk = np.sqrt(mse_sk)
r2 = r2_score(y_test, y_pred_sklearn)

print("MAE :", mae_sk)
print("MSE :", mse_sk)
print("RMSE:", rmse_sk)
print("R²  :", r2)

MAE : 408.1660511679643
MSE : 617588.9755669263
RMSE: 785.8682940333745
R²  : 0.96068739084825


## Compare Scratch KNN and Sklearn KNN

In [91]:
compare = pd.DataFrame({'Model': ['Scratch KNN', 'Sklearn KNN'],
                        'MAE': [mae_sc, mae_sk],
                        'RMSE': [rmse_sc, rmse_sk]})
compare

Model          MAE         RMSE
0  Scratch KNN  3276.237864  4365.137214
1  Sklearn KNN   408.166051   785.868294

##  Conclusion 

* KNN regression was successfully implemented **from scratch** to predict diamond prices.
* Categorical features were **encoded** and numerical features were **scaled** to improve distance calculation.
* The scratch KNN model produced **reasonable predictions** on test data.
* Model performance was evaluated using **MAE, MSE, RMSE, and R² score**.
* Sklearn’s KNN performed **slightly better and faster** due to optimization.
* The scratch implementation helped in understanding the **working of KNN internally**.
